###服务启动端口号
server:
  port: 8011
  tomcat:
    max-threads: 10
###服务名称(服务注册到eureka名称)
spring:
    application:
        name: com-zql-order
###服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://localhost:9100/eureka
###因为该应用为注册中心，不会注册自己
    register-with-eureka: true
###是否需要从eureka上获取注册信息
    fetch-registry: true

#设置feign客户端超时时间（Feign整合了ribbon本地负载均衡工具）
ribbon:
  #建立连接超时时间
  ReadTimeout: 5000
  #建立连接后请求资源超时时间
  ConnectTimeout: 5000

#开启Hytrix断路器
feign:
  hystrix:
    enable: true
  commond:
    execution
#配置hystrix调用超时时间
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 4000 //设置Hystrix的超时时间为4s
